name: Get Metrics JSON File
on: [push]
jobs:
    get-metric-job:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Generate JSON File with Repo Data Metric
              run: | 
                echo "### Count: Stargazer###"
                gh repo view DesignLiquido/delegua --json stargazerCount > stargazerCount.json

                echo "### Count: Watchers ###"
                gh repo view DesignLiquido/delegua --json watchers > watchersCount.json

                echo "### Count: Fork ###"
                gh repo view DesignLiquido/delegua --json forkCount > forkCount.json

                echo "### Last release ###"
                gh release view --repo DesignLiquido/delegua --json name,tagName,publishedAt,url > lastReleaseData.json

                echo "### Contributors Count ###"
                gh api repos/DesignLiquido/delegua/contributors --paginate | jq length > contriburosCount.json

                echo "### Issues Count - OPEN ###"
                gh api 'search/issues?q=repo:DesignLiquido/delegua+is:issue+is:open' --jq '.total_count' > openIssuesCount.json

                echo "### Issues Count - CLOSED ###"
                gh api 'search/issues?q=repo:DesignLiquido/delegua+is:issue+is:closed' --jq '.total_count' > closedIssuesCount.json

                echo "### PR Count - OPEN ###"
                gh api 'search/issues?q=repo:DesignLiquido/delegua+is:pr+is:open' --jq '.total_count' > openPRsCount.json

                echo "### PR Count - CLOSED ###"
                gh api 'search/issues?q=repo:DesignLiquido/delegua+is:pr+is:closed' --jq '.total_count' > closedPRsCount.json

                echo "### Community Standards ###"
                gh api repos/DesignLiquido/delegua/community/profile > communityStandards.json
                gh repo view DesignLiquido/delegua --json isSecurityPolicyEnabled > security.json

              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Upload stargazerCount.json
              uses: actions/upload-artifact@v5
              with:
                name: stargazerCount
                path: stargazerCount.json
          
            - name: Upload watchersCount.json
              uses: actions/upload-artifact@v5
              with:
                name: watchersCount
                path: watchersCount.json
            
            - name: Upload forkCount.json
              uses: actions/upload-artifact@v5
              with:
                name: forkCount
                path: forkCount.json
          
            - name: Upload lastReleaseData.json
              uses: actions/upload-artifact@v5
              with:
                name: lastReleaseData
                path: lastReleaseData.json

            - name: Upload contriburosCount.json
              uses: actions/upload-artifact@v5
              with:
                name: contriburosCount
                path: contriburosCount.json

            - name: Upload openIssuesCount.json
              uses: actions/upload-artifact@v5
              with:
                name: openIssuesCount
                path: openIssuesCount.json

            - name: Upload closedIssuesCount.json
              uses: actions/upload-artifact@v5
              with:
                name: closedIssuesCount
                path: closedIssuesCount.json

            - name: Upload openPRsCount.json
              uses: actions/upload-artifact@v5
              with:
                name: openPRsCount
                path: openPRsCount.json

            - name: Upload closedPRsCount.json
              uses: actions/upload-artifact@v5
              with:
                name: closedPRsCount
                path: closedPRsCount.json
    
            - name: Upload communityStandards.json
              uses: actions/upload-artifact@v5
              with:
                name: communityStandards
                path: communityStandards.json

            - name: Upload security.json
              uses: actions/upload-artifact@v5
              with:
                name: security
                path: security.json
